// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4SBejeEkSLNhgPOLtXOkAHQc7fLRiJok',
    appId: '1:744508919883:web:37b36f5b16e66278d77dce',
    messagingSenderId: '744508919883',
    projectId: 'spar-464a9',
    authDomain: 'spar-464a9.firebaseapp.com',
    databaseURL: 'https://spar-464a9-default-rtdb.firebaseio.com',
    storageBucket: 'spar-464a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCXxoDlYSj_NiqNvd-3Swczno70eaunbs',
    appId: '1:744508919883:android:68e8d13e99ae94ebd77dce',
    messagingSenderId: '744508919883',
    projectId: 'spar-464a9',
    databaseURL: 'https://spar-464a9-default-rtdb.firebaseio.com',
    storageBucket: 'spar-464a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU0ZMMoaCHs0IEo_1FiqmUhplVzZxb41o',
    appId: '1:744508919883:ios:db1b4a142cdcf248d77dce',
    messagingSenderId: '744508919883',
    projectId: 'spar-464a9',
    databaseURL: 'https://spar-464a9-default-rtdb.firebaseio.com',
    storageBucket: 'spar-464a9.appspot.com',
    iosBundleId: 'com.example.wasteManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU0ZMMoaCHs0IEo_1FiqmUhplVzZxb41o',
    appId: '1:744508919883:ios:db1b4a142cdcf248d77dce',
    messagingSenderId: '744508919883',
    projectId: 'spar-464a9',
    databaseURL: 'https://spar-464a9-default-rtdb.firebaseio.com',
    storageBucket: 'spar-464a9.appspot.com',
    iosBundleId: 'com.example.wasteManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4SBejeEkSLNhgPOLtXOkAHQc7fLRiJok',
    appId: '1:744508919883:web:244f4dc0dabccad2d77dce',
    messagingSenderId: '744508919883',
    projectId: 'spar-464a9',
    authDomain: 'spar-464a9.firebaseapp.com',
    databaseURL: 'https://spar-464a9-default-rtdb.firebaseio.com',
    storageBucket: 'spar-464a9.appspot.com',
  );

}