// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0xCeIcciLzUfEJ51m6d7WEk0-o8UstdQ',
    appId: '1:50631697180:web:d6d0c1556f47ca97bb10d9',
    messagingSenderId: '50631697180',
    projectId: 'waste-e0038',
    authDomain: 'waste-e0038.firebaseapp.com',
    databaseURL: 'https://waste-e0038-default-rtdb.firebaseio.com',
    storageBucket: 'waste-e0038.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE1SRONjw5yGDhASLs0Wm3eeolyYPvunk',
    appId: '1:50631697180:android:7eebd197b521751fbb10d9',
    messagingSenderId: '50631697180',
    projectId: 'waste-e0038',
    databaseURL: 'https://waste-e0038-default-rtdb.firebaseio.com',
    storageBucket: 'waste-e0038.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYoxambOt1nGS5crk2jdPiAAK4krJ1vrA',
    appId: '1:50631697180:ios:27aabc83a052d7a6bb10d9',
    messagingSenderId: '50631697180',
    projectId: 'waste-e0038',
    databaseURL: 'https://waste-e0038-default-rtdb.firebaseio.com',
    storageBucket: 'waste-e0038.appspot.com',
    iosBundleId: 'com.example.wasteManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYoxambOt1nGS5crk2jdPiAAK4krJ1vrA',
    appId: '1:50631697180:ios:27aabc83a052d7a6bb10d9',
    messagingSenderId: '50631697180',
    projectId: 'waste-e0038',
    databaseURL: 'https://waste-e0038-default-rtdb.firebaseio.com',
    storageBucket: 'waste-e0038.appspot.com',
    iosBundleId: 'com.example.wasteManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0xCeIcciLzUfEJ51m6d7WEk0-o8UstdQ',
    appId: '1:50631697180:web:287efce1d81a8f5dbb10d9',
    messagingSenderId: '50631697180',
    projectId: 'waste-e0038',
    authDomain: 'waste-e0038.firebaseapp.com',
    databaseURL: 'https://waste-e0038-default-rtdb.firebaseio.com',
    storageBucket: 'waste-e0038.appspot.com',
  );
}
